'''
The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to
have over five divisors.

What is the value of the first triangle number to
have over five hundred divisors?
'''

import numpy as np

def naive():
    def generateTriangleNumbers(num):
        numbers = []

        for i in range(1, num+1):
            
            total = 0
            
            for j in range(1,i+1):

                total += j

            numbers.append(total)     

        return numbers

def numDivisors(x):
    count = 0

    loopEnd = int(np.sqrt(x))
    # loopEnd = int(x / 2)

    for i in range(1, loopEnd+1):
        if x % i == 0:
            # print(i)
            count += 2

    return count

print('count', numDivisors(28))

x = 0
current = 1
while numDivisors(x) < 500:
    if current % 50 == 0:
        print(numDivisors(x))

    print(x)
    x += current
    current += 1


print('solution:', x)
print('num divisors: ', numDivisors(x))

    
