'''
Each new term in the Fibonacci sequence is generated by
adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose
values do not exceed four million,
find the sum of the even-valued terms.
'''

maxValue = 4000000
n0, n1, nx = 0, 1, 0

evens = []

while nx < maxValue:
    nx = n0 + n1
    n0 = n1
    n1 = nx

    if nx % 2 == 0:
        evens.append(nx)

print(sum(evens))



